// Test bench generated by generator_verilog.py

`timescale 1ns / 1ps

module SectorProcessor_test();

reg clk;
reg reset;

initial begin
  reset = 1'b1;
  clk   = 1'b1;
end

initial begin
  #1080
  reset = 1'b0;
end

reg en_proc = 1'b0;
always @(posedge clk) begin
  if (reset) en_proc = 1'b0;
  else       en_proc = 1'b1;
end

always begin
  #2.5 clk = ~clk;
end

reg [2:0] bx_in_ProjectionRouter;
initial bx_in_ProjectionRouter = 3'b110;
always begin
  #540 bx_in_ProjectionRouter <= bx_in_ProjectionRouter + 1'b1;
end
wire[2:0] bx_out_ProjectionRouter;

reg TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_ena;
reg TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_wea;
wire[7:0] TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_writeaddr;
wire[59:0] TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_din;
wire TPROJ_L1L2XXG_L3PHIC_nentries_0_V_we;
wire[7:0] TPROJ_L1L2XXG_L3PHIC_nentries_0_V_din;
wire TPROJ_L1L2XXG_L3PHIC_nentries_1_V_we;
wire[7:0] TPROJ_L1L2XXG_L3PHIC_nentries_1_V_din;
wire TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_enb;
wire[7:0] TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_readaddr;
wire[59:0] TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_dout;
wire[7:0] TPROJ_L1L2XXG_L3PHIC_nentries_0_V_dout;
wire[7:0] TPROJ_L1L2XXG_L3PHIC_nentries_1_V_dout;

initial begin
  TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_ena = 1'b1;
  TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_wea = 1'b0;
end

reg[7:0] Gnentries0 = 8'b00001110;
reg[7:0] Gnentries1 = 8'b00001001;
assign TPROJ_L1L2XXG_L3PHIC_nentries_0_V_dout = Gnentries0;
assign TPROJ_L1L2XXG_L3PHIC_nentries_1_V_dout = Gnentries1;

Memory #(
  .RAM_WIDTH(60),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("/mnt/scratch/djc448/firmware-tests/PR_Test/sourceFiles/TrackletProjections_TPROJ_L1L2G_L3PHIC_04_mod.dat")
) TPROJ_L1L2XXG_L3PHIC (
  .clka(clk),
  .clkb(clk),
//  .data_ena(TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_ena),
  .data_wea(TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_wea),
  .data_addra(TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_writeaddr),
  .data_dina(TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_din),
//  .nent_0_we(TPROJ_L1L2XXG_L3PHIC_nentries_0_V_we),
//  .nent_0_din(TPROJ_L1L2XXG_L3PHIC_nentries_0_V_din),
//  .nent_1_we(TPROJ_L1L2XXG_L3PHIC_nentries_1_V_we),
//  .nent_1_din(TPROJ_L1L2XXG_L3PHIC_nentries_1_V_din),
  .data_enb(TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_enb),
  .data_addrb(TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_readaddr),
  .data_doutb(TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_dout),
//  .nent_0_dout(TPROJ_L1L2XXG_L3PHIC_nentries_0_V_dout),
//  .nent_1_dout(TPROJ_L1L2XXG_L3PHIC_nentries_1_V_dout),
  .regceb(1'b1)
);

wire TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_ena;
wire TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_wea;
wire[7:0] TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_writeaddr;
wire[59:0] TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_din;
wire TPROJ_L1L2XXH_L3PHIC_nentries_0_V_we;
wire[7:0] TPROJ_L1L2XXH_L3PHIC_nentries_0_V_din;
wire TPROJ_L1L2XXH_L3PHIC_nentries_1_V_we;
wire[7:0] TPROJ_L1L2XXH_L3PHIC_nentries_1_V_din;
wire TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_enb;
wire[7:0] TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_readaddr;
wire[59:0] TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_dout;
wire[7:0] TPROJ_L1L2XXH_L3PHIC_nentries_0_V_dout;
wire[7:0] TPROJ_L1L2XXH_L3PHIC_nentries_1_V_dout;

reg[7:0] Hnentries0 = 8'b00001010;
reg[7:0] Hnentries1 = 8'b00000100;
assign TPROJ_L1L2XXH_L3PHIC_nentries_0_V_dout = Hnentries0;
assign TPROJ_L1L2XXH_L3PHIC_nentries_1_V_dout = Hnentries1;

Memory #(
  .RAM_WIDTH(60),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("/mnt/scratch/djc448/firmware-tests/PR_Test/sourceFiles/TrackletProjections_TPROJ_L1L2H_L3PHIC_04_mod.dat")
) TPROJ_L1L2XXH_L3PHIC (
  .clka(clk),
  .clkb(clk),
//  .data_ena(TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_ena),
  .data_wea(TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_wea),
  .data_addra(TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_writeaddr),
  .data_dina(TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_din),
//  .nent_0_we(TPROJ_L1L2XXH_L3PHIC_nentries_0_V_we),
//  .nent_0_din(TPROJ_L1L2XXH_L3PHIC_nentries_0_V_din),
//  .nent_1_we(TPROJ_L1L2XXH_L3PHIC_nentries_1_V_we),
//  .nent_1_din(TPROJ_L1L2XXH_L3PHIC_nentries_1_V_din),
  .data_enb(TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_enb),
  .data_addrb(TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_readaddr),
  .data_doutb(TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_dout),
//  .nent_0_dout(TPROJ_L1L2XXH_L3PHIC_nentries_0_V_dout),
//  .nent_1_dout(TPROJ_L1L2XXH_L3PHIC_nentries_1_V_dout),
  .regceb(1'b1)
);

wire TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_ena;
wire TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_wea;
wire[7:0] TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_writeaddr;
wire[59:0] TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_din;
wire TPROJ_L5L6XXB_L3PHIC_nentries_0_V_we;
wire[7:0] TPROJ_L5L6XXB_L3PHIC_nentries_0_V_din;
wire TPROJ_L5L6XXB_L3PHIC_nentries_1_V_we;
wire[7:0] TPROJ_L5L6XXB_L3PHIC_nentries_1_V_din;
wire TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_enb;
wire[7:0] TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_readaddr;
wire[59:0] TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_dout;
wire[7:0] TPROJ_L5L6XXB_L3PHIC_nentries_0_V_dout;
wire[7:0] TPROJ_L5L6XXB_L3PHIC_nentries_1_V_dout;

reg[7:0] Bnentries0 = 8'b00000000;
reg[7:0] Bnentries1 = 8'b00000000;
assign TPROJ_L5L6XXB_L3PHIC_nentries_0_V_dout = Bnentries0;
assign TPROJ_L5L6XXB_L3PHIC_nentries_1_V_dout = Bnentries1;

Memory #(
  .RAM_WIDTH(60),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("/mnt/scratch/djc448/firmware-tests/PR_Test/sourceFiles/TrackletProjections_TPROJ_L5L6B_L3PHIC_04_mod.dat")
) TPROJ_L5L6XXB_L3PHIC (
  .clka(clk),
  .clkb(clk),
//  .data_ena(TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_ena),
  .data_wea(TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_wea),
  .data_addra(TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_writeaddr),
  .data_dina(TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_din),
//  .nent_0_we(TPROJ_L5L6XXB_L3PHIC_nentries_0_V_we),
//  .nent_0_din(TPROJ_L5L6XXB_L3PHIC_nentries_0_V_din),
//  .nent_1_we(TPROJ_L5L6XXB_L3PHIC_nentries_1_V_we),
//  .nent_1_din(TPROJ_L5L6XXB_L3PHIC_nentries_1_V_din),
  .data_enb(TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_enb),
  .data_addrb(TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_readaddr),
  .data_doutb(TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_dout),
//  .nent_0_dout(TPROJ_L5L6XXB_L3PHIC_nentries_0_V_dout),
//  .nent_1_dout(TPROJ_L5L6XXB_L3PHIC_nentries_1_V_dout),
  .regceb(1'b1)
);

wire TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_ena;
wire TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_wea;
wire[7:0] TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_writeaddr;
wire[59:0] TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_din;
wire TPROJ_L5L6XXC_L3PHIC_nentries_0_V_we;
wire[7:0] TPROJ_L5L6XXC_L3PHIC_nentries_0_V_din;
wire TPROJ_L5L6XXC_L3PHIC_nentries_1_V_we;
wire[7:0] TPROJ_L5L6XXC_L3PHIC_nentries_1_V_din;
wire TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_enb;
wire[7:0] TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_readaddr;
wire[59:0] TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_dout;
wire[7:0] TPROJ_L5L6XXC_L3PHIC_nentries_0_V_dout;
wire[7:0] TPROJ_L5L6XXC_L3PHIC_nentries_1_V_dout;

reg[7:0] Cnentries0 = 8'b00000000;
reg[7:0] Cnentries1 = 8'b00000000;
assign TPROJ_L5L6XXC_L3PHIC_nentries_0_V_dout = Cnentries0;
assign TPROJ_L5L6XXC_L3PHIC_nentries_1_V_dout = Cnentries1;

Memory #(
  .RAM_WIDTH(60),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("/mnt/scratch/djc448/firmware-tests/PR_Test/sourceFiles/TrackletProjections_TPROJ_L5L6C_L3PHIC_04_mod.dat")
) TPROJ_L5L6XXC_L3PHIC (
  .clka(clk),
  .clkb(clk),
//  .data_ena(TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_ena),
  .data_wea(TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_wea),
  .data_addra(TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_writeaddr),
  .data_dina(TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_din),
//  .nent_0_we(TPROJ_L5L6XXC_L3PHIC_nentries_0_V_we),
//  .nent_0_din(TPROJ_L5L6XXC_L3PHIC_nentries_0_V_din),
//  .nent_1_we(TPROJ_L5L6XXC_L3PHIC_nentries_1_V_we),
//  .nent_1_din(TPROJ_L5L6XXC_L3PHIC_nentries_1_V_din),
  .data_enb(TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_enb),
  .data_addrb(TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_readaddr),
  .data_doutb(TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_dout),
//  .nent_0_dout(TPROJ_L5L6XXC_L3PHIC_nentries_0_V_dout),
//  .nent_1_dout(TPROJ_L5L6XXC_L3PHIC_nentries_1_V_dout),
  .regceb(1'b1)
);

wire TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_ena;
wire TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_wea;
wire[7:0] TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_writeaddr;
wire[59:0] TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_din;
wire TPROJ_L5L6XXD_L3PHIC_nentries_0_V_we;
wire[7:0] TPROJ_L5L6XXD_L3PHIC_nentries_0_V_din;
wire TPROJ_L5L6XXD_L3PHIC_nentries_1_V_we;
wire[7:0] TPROJ_L5L6XXD_L3PHIC_nentries_1_V_din;
wire TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_enb;
wire[7:0] TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_readaddr;
wire[59:0] TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_dout;
wire[7:0] TPROJ_L5L6XXD_L3PHIC_nentries_0_V_dout;
wire[7:0] TPROJ_L5L6XXD_L3PHIC_nentries_1_V_dout;

reg[7:0] Dnentries0 = 8'b00000001;
reg[7:0] Dnentries1 = 8'b00000001;
assign TPROJ_L5L6XXD_L3PHIC_nentries_0_V_dout = Dnentries0;
assign TPROJ_L5L6XXD_L3PHIC_nentries_1_V_dout = Dnentries1;

Memory #(
  .RAM_WIDTH(60),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("/mnt/scratch/djc448/firmware-tests/PR_Test/sourceFiles/TrackletProjections_TPROJ_L5L6D_L3PHIC_04_mod.dat")
) TPROJ_L5L6XXD_L3PHIC (
  .clka(clk),
  .clkb(clk),
//  .data_ena(TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_ena),
  .data_wea(TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_wea),
  .data_addra(TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_writeaddr),
  .data_dina(TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_din),
//  .nent_0_we(TPROJ_L5L6XXD_L3PHIC_nentries_0_V_we),
//  .nent_0_din(TPROJ_L5L6XXD_L3PHIC_nentries_0_V_din),
//  .nent_1_we(TPROJ_L5L6XXD_L3PHIC_nentries_1_V_we),
//  .nent_1_din(TPROJ_L5L6XXD_L3PHIC_nentries_1_V_din),
  .data_enb(TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_enb),
  .data_addrb(TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_readaddr),
  .data_doutb(TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_dout),
//  .nent_0_dout(TPROJ_L5L6XXD_L3PHIC_nentries_0_V_dout),
//  .nent_1_dout(TPROJ_L5L6XXD_L3PHIC_nentries_1_V_dout),
  .regceb(1'b1)
);

wire TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_ena;
wire TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_wea;
wire[7:0] TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_writeaddr;
wire[59:0] TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_din;
wire TPROJ_L1L2XXF_L3PHIC_nentries_0_V_we;
wire[7:0] TPROJ_L1L2XXF_L3PHIC_nentries_0_V_din;
wire TPROJ_L1L2XXF_L3PHIC_nentries_1_V_we;
wire[7:0] TPROJ_L1L2XXF_L3PHIC_nentries_1_V_din;
wire TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_enb;
wire[7:0] TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_readaddr;
wire[59:0] TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_dout;
wire[7:0] TPROJ_L1L2XXF_L3PHIC_nentries_0_V_dout;
wire[7:0] TPROJ_L1L2XXF_L3PHIC_nentries_1_V_dout;

reg[7:0] Fnentries0 = 8'b00000000;
reg[7:0] Fnentries1 = 8'b00000000;
assign TPROJ_L1L2XXF_L3PHIC_nentries_0_V_dout = Fnentries0;
assign TPROJ_L1L2XXF_L3PHIC_nentries_1_V_dout = Fnentries1;

Memory #(
  .RAM_WIDTH(60),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("/mnt/scratch/djc448/firmware-tests/PR_Test/sourceFiles/TrackletProjections_TPROJ_L1L2F_L3PHIC_04_mod.dat")
) TPROJ_L1L2XXF_L3PHIC (
  .clka(clk),
  .clkb(clk),
//  .data_ena(TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_ena),
  .data_wea(TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_wea),
  .data_addra(TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_writeaddr),
  .data_dina(TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_din),
//  .nent_0_we(TPROJ_L1L2XXF_L3PHIC_nentries_0_V_we),
//  .nent_0_din(TPROJ_L1L2XXF_L3PHIC_nentries_0_V_din),
//  .nent_1_we(TPROJ_L1L2XXF_L3PHIC_nentries_1_V_we),
//  .nent_1_din(TPROJ_L1L2XXF_L3PHIC_nentries_1_V_din),
  .data_enb(TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_enb),
  .data_addrb(TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_readaddr),
  .data_doutb(TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_dout),
//  .nent_0_dout(TPROJ_L1L2XXF_L3PHIC_nentries_0_V_dout),
//  .nent_1_dout(TPROJ_L1L2XXF_L3PHIC_nentries_1_V_dout),
  .regceb(1'b1)
);

wire TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_ena;
wire TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_wea;
wire[7:0] TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_writeaddr;
wire[59:0] TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_din;
wire TPROJ_L1L2XXJ_L3PHIC_nentries_0_V_we;
wire[7:0] TPROJ_L1L2XXJ_L3PHIC_nentries_0_V_din;
wire TPROJ_L1L2XXJ_L3PHIC_nentries_1_V_we;
wire[7:0] TPROJ_L1L2XXJ_L3PHIC_nentries_1_V_din;
wire TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_enb;
wire[7:0] TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_readaddr;
wire[59:0] TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_dout;
wire[7:0] TPROJ_L1L2XXJ_L3PHIC_nentries_0_V_dout;
wire[7:0] TPROJ_L1L2XXJ_L3PHIC_nentries_1_V_dout;

reg[7:0] Jnentries0 = 8'b00000001;
reg[7:0] Jnentries1 = 8'b00000000;
assign TPROJ_L1L2XXJ_L3PHIC_nentries_0_V_dout = Jnentries0;
assign TPROJ_L1L2XXJ_L3PHIC_nentries_1_V_dout = Jnentries1;

Memory #(
  .RAM_WIDTH(60),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("/mnt/scratch/djc448/firmware-tests/PR_Test/sourceFiles/TrackletProjections_TPROJ_L1L2J_L3PHIC_04_mod.dat")
) TPROJ_L1L2XXJ_L3PHIC (
  .clka(clk),
  .clkb(clk),
//  .data_ena(TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_ena),
  .data_wea(TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_wea),
  .data_addra(TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_writeaddr),
  .data_dina(TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_din),
//  .nent_0_we(TPROJ_L1L2XXJ_L3PHIC_nentries_0_V_we),
//  .nent_0_din(TPROJ_L1L2XXJ_L3PHIC_nentries_0_V_din),
//  .nent_1_we(TPROJ_L1L2XXJ_L3PHIC_nentries_1_V_we),
//  .nent_1_din(TPROJ_L1L2XXJ_L3PHIC_nentries_1_V_din),
  .data_enb(TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_enb),
  .data_addrb(TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_readaddr),
  .data_doutb(TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_dout),
//  .nent_0_dout(TPROJ_L1L2XXJ_L3PHIC_nentries_0_V_dout),
//  .nent_1_dout(TPROJ_L1L2XXJ_L3PHIC_nentries_1_V_dout),
  .regceb(1'b1)
);

wire TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_ena;
wire TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_wea;
wire[7:0] TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_writeaddr;
wire[59:0] TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_din;
wire TPROJ_L1L2XXI_L3PHIC_nentries_0_V_we;
wire[7:0] TPROJ_L1L2XXI_L3PHIC_nentries_0_V_din;
wire TPROJ_L1L2XXI_L3PHIC_nentries_1_V_we;
wire[7:0] TPROJ_L1L2XXI_L3PHIC_nentries_1_V_din;
wire TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_enb;
wire[7:0] TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_readaddr;
wire[59:0] TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_dout;
wire[7:0] TPROJ_L1L2XXI_L3PHIC_nentries_0_V_dout;
wire[7:0] TPROJ_L1L2XXI_L3PHIC_nentries_1_V_dout;

reg[7:0] Inentries0 = 8'b00000010;
reg[7:0] Inentries1 = 8'b00000000;
assign TPROJ_L1L2XXI_L3PHIC_nentries_0_V_dout = Inentries0;
assign TPROJ_L1L2XXI_L3PHIC_nentries_1_V_dout = Inentries1;

Memory #(
  .RAM_WIDTH(60),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("/mnt/scratch/djc448/firmware-tests/PR_Test/sourceFiles/TrackletProjections_TPROJ_L1L2I_L3PHIC_04_mod.dat")
) TPROJ_L1L2XXI_L3PHIC (
  .clka(clk),
  .clkb(clk),
//  .data_ena(TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_ena),
  .data_wea(TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_wea),
  .data_addra(TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_writeaddr),
  .data_dina(TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_din),
//  .nent_0_we(TPROJ_L1L2XXI_L3PHIC_nentries_0_V_we),
//  .nent_0_din(TPROJ_L1L2XXI_L3PHIC_nentries_0_V_din),
//  .nent_1_we(TPROJ_L1L2XXI_L3PHIC_nentries_1_V_we),
//  .nent_1_din(TPROJ_L1L2XXI_L3PHIC_nentries_1_V_din),
  .data_enb(TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_enb),
  .data_addrb(TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_readaddr),
  .data_doutb(TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_dout),
//  .nent_0_dout(TPROJ_L1L2XXI_L3PHIC_nentries_0_V_dout),
//  .nent_1_dout(TPROJ_L1L2XXI_L3PHIC_nentries_1_V_dout),
  .regceb(1'b1)
);

wire VMPROJ_L3PHIC20_dataarray_data_V_ena;
wire VMPROJ_L3PHIC20_dataarray_data_V_wea;
wire[7:0] VMPROJ_L3PHIC20_dataarray_data_V_writeaddr;
wire[20:0] VMPROJ_L3PHIC20_dataarray_data_V_din;
wire VMPROJ_L3PHIC20_nentries_0_V_we;
wire[7:0] VMPROJ_L3PHIC20_nentries_0_V_din;
wire VMPROJ_L3PHIC20_nentries_1_V_we;
wire[7:0] VMPROJ_L3PHIC20_nentries_1_V_din;
wire VMPROJ_L3PHIC20_dataarray_data_V_enb;
wire[7:0] VMPROJ_L3PHIC20_dataarray_data_V_readaddr;
wire[20:0] VMPROJ_L3PHIC20_dataarray_data_V_dout;
wire[7:0] VMPROJ_L3PHIC20_nentries_0_V_dout;
wire[7:0] VMPROJ_L3PHIC20_nentries_1_V_dout;

Memory #(
  .RAM_WIDTH(21),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("")
) VMPROJ_L3PHIC20 (
  .clka(clk),
  .clkb(clk),
//  .data_ena(VMPROJ_L3PHIC20_dataarray_data_V_ena),
  .data_wea(VMPROJ_L3PHIC20_dataarray_data_V_wea),
  .data_addra(VMPROJ_L3PHIC20_dataarray_data_V_writeaddr),
  .data_dina(VMPROJ_L3PHIC20_dataarray_data_V_din),
//  .nent_0_we(VMPROJ_L3PHIC20_nentries_0_V_we),
//  .nent_0_din(VMPROJ_L3PHIC20_nentries_0_V_din),
//  .nent_1_we(VMPROJ_L3PHIC20_nentries_1_V_we),
//  .nent_1_din(VMPROJ_L3PHIC20_nentries_1_V_din),
  .data_enb(VMPROJ_L3PHIC20_dataarray_data_V_enb),
  .data_addrb(VMPROJ_L3PHIC20_dataarray_data_V_readaddr),
  .data_doutb(VMPROJ_L3PHIC20_dataarray_data_V_dout),
//  .nent_0_dout(VMPROJ_L3PHIC20_nentries_0_V_dout),
//  .nent_1_dout(VMPROJ_L3PHIC20_nentries_1_V_dout),
  .regceb(1'b1)
);

wire VMPROJ_L3PHIC17_dataarray_data_V_ena;
wire VMPROJ_L3PHIC17_dataarray_data_V_wea;
wire[7:0] VMPROJ_L3PHIC17_dataarray_data_V_writeaddr;
wire[20:0] VMPROJ_L3PHIC17_dataarray_data_V_din;
wire VMPROJ_L3PHIC17_nentries_0_V_we;
wire[7:0] VMPROJ_L3PHIC17_nentries_0_V_din;
wire VMPROJ_L3PHIC17_nentries_1_V_we;
wire[7:0] VMPROJ_L3PHIC17_nentries_1_V_din;
wire VMPROJ_L3PHIC17_dataarray_data_V_enb;
wire[7:0] VMPROJ_L3PHIC17_dataarray_data_V_readaddr;
wire[20:0] VMPROJ_L3PHIC17_dataarray_data_V_dout;
wire[7:0] VMPROJ_L3PHIC17_nentries_0_V_dout;
wire[7:0] VMPROJ_L3PHIC17_nentries_1_V_dout;

Memory #(
  .RAM_WIDTH(21),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("")
) VMPROJ_L3PHIC17 (
  .clka(clk),
  .clkb(clk),
//  .data_ena(VMPROJ_L3PHIC17_dataarray_data_V_ena),
  .data_wea(VMPROJ_L3PHIC17_dataarray_data_V_wea),
  .data_addra(VMPROJ_L3PHIC17_dataarray_data_V_writeaddr),
  .data_dina(VMPROJ_L3PHIC17_dataarray_data_V_din),
//  .nent_0_we(VMPROJ_L3PHIC17_nentries_0_V_we),
//  .nent_0_din(VMPROJ_L3PHIC17_nentries_0_V_din),
//  .nent_1_we(VMPROJ_L3PHIC17_nentries_1_V_we),
//  .nent_1_din(VMPROJ_L3PHIC17_nentries_1_V_din),
  .data_enb(VMPROJ_L3PHIC17_dataarray_data_V_enb),
  .data_addrb(VMPROJ_L3PHIC17_dataarray_data_V_readaddr),
  .data_doutb(VMPROJ_L3PHIC17_dataarray_data_V_dout),
//  .nent_0_dout(VMPROJ_L3PHIC17_nentries_0_V_dout),
//  .nent_1_dout(VMPROJ_L3PHIC17_nentries_1_V_dout),
  .regceb(1'b1)
);

wire VMPROJ_L3PHIC22_dataarray_data_V_ena;
wire VMPROJ_L3PHIC22_dataarray_data_V_wea;
wire[7:0] VMPROJ_L3PHIC22_dataarray_data_V_writeaddr;
wire[20:0] VMPROJ_L3PHIC22_dataarray_data_V_din;
wire VMPROJ_L3PHIC22_nentries_0_V_we;
wire[7:0] VMPROJ_L3PHIC22_nentries_0_V_din;
wire VMPROJ_L3PHIC22_nentries_1_V_we;
wire[7:0] VMPROJ_L3PHIC22_nentries_1_V_din;
wire VMPROJ_L3PHIC22_dataarray_data_V_enb;
wire[7:0] VMPROJ_L3PHIC22_dataarray_data_V_readaddr;
wire[20:0] VMPROJ_L3PHIC22_dataarray_data_V_dout;
wire[7:0] VMPROJ_L3PHIC22_nentries_0_V_dout;
wire[7:0] VMPROJ_L3PHIC22_nentries_1_V_dout;

Memory #(
  .RAM_WIDTH(21),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("")
) VMPROJ_L3PHIC22 (
  .clka(clk),
  .clkb(clk),
//  .data_ena(VMPROJ_L3PHIC22_dataarray_data_V_ena),
  .data_wea(VMPROJ_L3PHIC22_dataarray_data_V_wea),
  .data_addra(VMPROJ_L3PHIC22_dataarray_data_V_writeaddr),
  .data_dina(VMPROJ_L3PHIC22_dataarray_data_V_din),
//  .nent_0_we(VMPROJ_L3PHIC22_nentries_0_V_we),
//  .nent_0_din(VMPROJ_L3PHIC22_nentries_0_V_din),
//  .nent_1_we(VMPROJ_L3PHIC22_nentries_1_V_we),
//  .nent_1_din(VMPROJ_L3PHIC22_nentries_1_V_din),
  .data_enb(VMPROJ_L3PHIC22_dataarray_data_V_enb),
  .data_addrb(VMPROJ_L3PHIC22_dataarray_data_V_readaddr),
  .data_doutb(VMPROJ_L3PHIC22_dataarray_data_V_dout),
//  .nent_0_dout(VMPROJ_L3PHIC22_nentries_0_V_dout),
//  .nent_1_dout(VMPROJ_L3PHIC22_nentries_1_V_dout),
  .regceb(1'b1)
);

wire VMPROJ_L3PHIC19_dataarray_data_V_ena;
wire VMPROJ_L3PHIC19_dataarray_data_V_wea;
wire[7:0] VMPROJ_L3PHIC19_dataarray_data_V_writeaddr;
wire[20:0] VMPROJ_L3PHIC19_dataarray_data_V_din;
wire VMPROJ_L3PHIC19_nentries_0_V_we;
wire[7:0] VMPROJ_L3PHIC19_nentries_0_V_din;
wire VMPROJ_L3PHIC19_nentries_1_V_we;
wire[7:0] VMPROJ_L3PHIC19_nentries_1_V_din;
wire VMPROJ_L3PHIC19_dataarray_data_V_enb;
wire[7:0] VMPROJ_L3PHIC19_dataarray_data_V_readaddr;
wire[20:0] VMPROJ_L3PHIC19_dataarray_data_V_dout;
wire[7:0] VMPROJ_L3PHIC19_nentries_0_V_dout;
wire[7:0] VMPROJ_L3PHIC19_nentries_1_V_dout;

Memory #(
  .RAM_WIDTH(21),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("")
) VMPROJ_L3PHIC19 (
  .clka(clk),
  .clkb(clk),
//  .data_ena(VMPROJ_L3PHIC19_dataarray_data_V_ena),
  .data_wea(VMPROJ_L3PHIC19_dataarray_data_V_wea),
  .data_addra(VMPROJ_L3PHIC19_dataarray_data_V_writeaddr),
  .data_dina(VMPROJ_L3PHIC19_dataarray_data_V_din),
//  .nent_0_we(VMPROJ_L3PHIC19_nentries_0_V_we),
//  .nent_0_din(VMPROJ_L3PHIC19_nentries_0_V_din),
//  .nent_1_we(VMPROJ_L3PHIC19_nentries_1_V_we),
//  .nent_1_din(VMPROJ_L3PHIC19_nentries_1_V_din),
  .data_enb(VMPROJ_L3PHIC19_dataarray_data_V_enb),
  .data_addrb(VMPROJ_L3PHIC19_dataarray_data_V_readaddr),
  .data_doutb(VMPROJ_L3PHIC19_dataarray_data_V_dout),
//  .nent_0_dout(VMPROJ_L3PHIC19_nentries_0_V_dout),
//  .nent_1_dout(VMPROJ_L3PHIC19_nentries_1_V_dout),
  .regceb(1'b1)
);

wire AP_L3PHIC_dataarray_data_V_ena;
wire AP_L3PHIC_dataarray_data_V_wea;
wire[9:0] AP_L3PHIC_dataarray_data_V_writeaddr;
wire[59:0] AP_L3PHIC_dataarray_data_V_din;
wire AP_L3PHIC_nentries_0_V_we;
wire[7:0] AP_L3PHIC_nentries_0_V_din;
wire AP_L3PHIC_nentries_1_V_we;
wire[7:0] AP_L3PHIC_nentries_1_V_din;
wire AP_L3PHIC_nentries_2_V_we;
wire[7:0] AP_L3PHIC_nentries_2_V_din;
wire AP_L3PHIC_nentries_3_V_we;
wire[7:0] AP_L3PHIC_nentries_3_V_din;
wire AP_L3PHIC_nentries_4_V_we;
wire[7:0] AP_L3PHIC_nentries_4_V_din;
wire AP_L3PHIC_nentries_5_V_we;
wire[7:0] AP_L3PHIC_nentries_5_V_din;
wire AP_L3PHIC_nentries_6_V_we;
wire[7:0] AP_L3PHIC_nentries_6_V_din;
wire AP_L3PHIC_nentries_7_V_we;
wire[7:0] AP_L3PHIC_nentries_7_V_din;
wire AP_L3PHIC_dataarray_data_V_enb;
wire[9:0] AP_L3PHIC_dataarray_data_V_readaddr;
wire[59:0] AP_L3PHIC_dataarray_data_V_dout;
wire[7:0] AP_L3PHIC_nentries_0_V_dout;
wire[7:0] AP_L3PHIC_nentries_1_V_dout;
wire[7:0] AP_L3PHIC_nentries_2_V_dout;
wire[7:0] AP_L3PHIC_nentries_3_V_dout;
wire[7:0] AP_L3PHIC_nentries_4_V_dout;
wire[7:0] AP_L3PHIC_nentries_5_V_dout;
wire[7:0] AP_L3PHIC_nentries_6_V_dout;
wire[7:0] AP_L3PHIC_nentries_7_V_dout;

Memory #(
  .RAM_WIDTH(60),
  .RAM_DEPTH(1024),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("")
) AP_L3PHIC (
  .clka(clk),
  .clkb(clk),
//  .data_ena(AP_L3PHIC_dataarray_data_V_ena),
  .data_wea(AP_L3PHIC_dataarray_data_V_wea),
  .data_addra(AP_L3PHIC_dataarray_data_V_writeaddr),
  .data_dina(AP_L3PHIC_dataarray_data_V_din),
//  .nent_0_we(AP_L3PHIC_nentries_0_V_we),
//  .nent_0_din(AP_L3PHIC_nentries_0_V_din),
//  .nent_1_we(AP_L3PHIC_nentries_1_V_we),
//  .nent_1_din(AP_L3PHIC_nentries_1_V_din),
//  .nent_2_we(AP_L3PHIC_nentries_2_V_we),
//  .nent_2_din(AP_L3PHIC_nentries_2_V_din),
//  .nent_3_we(AP_L3PHIC_nentries_3_V_we),
//  .nent_3_din(AP_L3PHIC_nentries_3_V_din),
//  .nent_4_we(AP_L3PHIC_nentries_4_V_we),
//  .nent_4_din(AP_L3PHIC_nentries_4_V_din),
//  .nent_5_we(AP_L3PHIC_nentries_5_V_we),
//  .nent_5_din(AP_L3PHIC_nentries_5_V_din),
//  .nent_6_we(AP_L3PHIC_nentries_6_V_we),
//  .nent_6_din(AP_L3PHIC_nentries_6_V_din),
//  .nent_7_we(AP_L3PHIC_nentries_7_V_we),
//  .nent_7_din(AP_L3PHIC_nentries_7_V_din),
  .data_enb(AP_L3PHIC_dataarray_data_V_enb),
  .data_addrb(AP_L3PHIC_dataarray_data_V_readaddr),
  .data_doutb(AP_L3PHIC_dataarray_data_V_dout),
//  .nent_0_dout(AP_L3PHIC_nentries_0_V_dout),
//  .nent_1_dout(AP_L3PHIC_nentries_1_V_dout),
//  .nent_2_dout(AP_L3PHIC_nentries_2_V_dout),
//  .nent_3_dout(AP_L3PHIC_nentries_3_V_dout),
//  .nent_4_dout(AP_L3PHIC_nentries_4_V_dout),
//  .nent_5_dout(AP_L3PHIC_nentries_5_V_dout),
//  .nent_6_dout(AP_L3PHIC_nentries_6_V_dout),
//  .nent_7_dout(AP_L3PHIC_nentries_7_V_dout),
  .regceb(1'b1)
);

wire VMPROJ_L3PHIC24_dataarray_data_V_ena;
wire VMPROJ_L3PHIC24_dataarray_data_V_wea;
wire[7:0] VMPROJ_L3PHIC24_dataarray_data_V_writeaddr;
wire[20:0] VMPROJ_L3PHIC24_dataarray_data_V_din;
wire VMPROJ_L3PHIC24_nentries_0_V_we;
wire[7:0] VMPROJ_L3PHIC24_nentries_0_V_din;
wire VMPROJ_L3PHIC24_nentries_1_V_we;
wire[7:0] VMPROJ_L3PHIC24_nentries_1_V_din;
wire VMPROJ_L3PHIC24_dataarray_data_V_enb;
wire[7:0] VMPROJ_L3PHIC24_dataarray_data_V_readaddr;
wire[20:0] VMPROJ_L3PHIC24_dataarray_data_V_dout;
wire[7:0] VMPROJ_L3PHIC24_nentries_0_V_dout;
wire[7:0] VMPROJ_L3PHIC24_nentries_1_V_dout;

Memory #(
  .RAM_WIDTH(21),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("")
) VMPROJ_L3PHIC24 (
  .clka(clk),
  .clkb(clk),
//  .data_ena(VMPROJ_L3PHIC24_dataarray_data_V_ena),
  .data_wea(VMPROJ_L3PHIC24_dataarray_data_V_wea),
  .data_addra(VMPROJ_L3PHIC24_dataarray_data_V_writeaddr),
  .data_dina(VMPROJ_L3PHIC24_dataarray_data_V_din),
//  .nent_0_we(VMPROJ_L3PHIC24_nentries_0_V_we),
//  .nent_0_din(VMPROJ_L3PHIC24_nentries_0_V_din),
//  .nent_1_we(VMPROJ_L3PHIC24_nentries_1_V_we),
//  .nent_1_din(VMPROJ_L3PHIC24_nentries_1_V_din),
  .data_enb(VMPROJ_L3PHIC24_dataarray_data_V_enb),
  .data_addrb(VMPROJ_L3PHIC24_dataarray_data_V_readaddr),
  .data_doutb(VMPROJ_L3PHIC24_dataarray_data_V_dout),
//  .nent_0_dout(VMPROJ_L3PHIC24_nentries_0_V_dout),
//  .nent_1_dout(VMPROJ_L3PHIC24_nentries_1_V_dout),
  .regceb(1'b1)
);

wire VMPROJ_L3PHIC23_dataarray_data_V_ena;
wire VMPROJ_L3PHIC23_dataarray_data_V_wea;
wire[7:0] VMPROJ_L3PHIC23_dataarray_data_V_writeaddr;
wire[20:0] VMPROJ_L3PHIC23_dataarray_data_V_din;
wire VMPROJ_L3PHIC23_nentries_0_V_we;
wire[7:0] VMPROJ_L3PHIC23_nentries_0_V_din;
wire VMPROJ_L3PHIC23_nentries_1_V_we;
wire[7:0] VMPROJ_L3PHIC23_nentries_1_V_din;
wire VMPROJ_L3PHIC23_dataarray_data_V_enb;
wire[7:0] VMPROJ_L3PHIC23_dataarray_data_V_readaddr;
wire[20:0] VMPROJ_L3PHIC23_dataarray_data_V_dout;
wire[7:0] VMPROJ_L3PHIC23_nentries_0_V_dout;
wire[7:0] VMPROJ_L3PHIC23_nentries_1_V_dout;

Memory #(
  .RAM_WIDTH(21),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("")
) VMPROJ_L3PHIC23 (
  .clka(clk),
  .clkb(clk),
//  .data_ena(VMPROJ_L3PHIC23_dataarray_data_V_ena),
  .data_wea(VMPROJ_L3PHIC23_dataarray_data_V_wea),
  .data_addra(VMPROJ_L3PHIC23_dataarray_data_V_writeaddr),
  .data_dina(VMPROJ_L3PHIC23_dataarray_data_V_din),
//  .nent_0_we(VMPROJ_L3PHIC23_nentries_0_V_we),
//  .nent_0_din(VMPROJ_L3PHIC23_nentries_0_V_din),
//  .nent_1_we(VMPROJ_L3PHIC23_nentries_1_V_we),
//  .nent_1_din(VMPROJ_L3PHIC23_nentries_1_V_din),
  .data_enb(VMPROJ_L3PHIC23_dataarray_data_V_enb),
  .data_addrb(VMPROJ_L3PHIC23_dataarray_data_V_readaddr),
  .data_doutb(VMPROJ_L3PHIC23_dataarray_data_V_dout),
//  .nent_0_dout(VMPROJ_L3PHIC23_nentries_0_V_dout),
//  .nent_1_dout(VMPROJ_L3PHIC23_nentries_1_V_dout),
  .regceb(1'b1)
);

wire VMPROJ_L3PHIC18_dataarray_data_V_ena;
wire VMPROJ_L3PHIC18_dataarray_data_V_wea;
wire[7:0] VMPROJ_L3PHIC18_dataarray_data_V_writeaddr;
wire[20:0] VMPROJ_L3PHIC18_dataarray_data_V_din;
wire VMPROJ_L3PHIC18_nentries_0_V_we;
wire[7:0] VMPROJ_L3PHIC18_nentries_0_V_din;
wire VMPROJ_L3PHIC18_nentries_1_V_we;
wire[7:0] VMPROJ_L3PHIC18_nentries_1_V_din;
wire VMPROJ_L3PHIC18_dataarray_data_V_enb;
wire[7:0] VMPROJ_L3PHIC18_dataarray_data_V_readaddr;
wire[20:0] VMPROJ_L3PHIC18_dataarray_data_V_dout;
wire[7:0] VMPROJ_L3PHIC18_nentries_0_V_dout;
wire[7:0] VMPROJ_L3PHIC18_nentries_1_V_dout;

Memory #(
  .RAM_WIDTH(21),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("")
) VMPROJ_L3PHIC18 (
  .clka(clk),
  .clkb(clk),
//  .data_ena(VMPROJ_L3PHIC18_dataarray_data_V_ena),
  .data_wea(VMPROJ_L3PHIC18_dataarray_data_V_wea),
  .data_addra(VMPROJ_L3PHIC18_dataarray_data_V_writeaddr),
  .data_dina(VMPROJ_L3PHIC18_dataarray_data_V_din),
//  .nent_0_we(VMPROJ_L3PHIC18_nentries_0_V_we),
//  .nent_0_din(VMPROJ_L3PHIC18_nentries_0_V_din),
//  .nent_1_we(VMPROJ_L3PHIC18_nentries_1_V_we),
//  .nent_1_din(VMPROJ_L3PHIC18_nentries_1_V_din),
  .data_enb(VMPROJ_L3PHIC18_dataarray_data_V_enb),
  .data_addrb(VMPROJ_L3PHIC18_dataarray_data_V_readaddr),
  .data_doutb(VMPROJ_L3PHIC18_dataarray_data_V_dout),
//  .nent_0_dout(VMPROJ_L3PHIC18_nentries_0_V_dout),
//  .nent_1_dout(VMPROJ_L3PHIC18_nentries_1_V_dout),
  .regceb(1'b1)
);

wire VMPROJ_L3PHIC21_dataarray_data_V_ena;
wire VMPROJ_L3PHIC21_dataarray_data_V_wea;
wire[7:0] VMPROJ_L3PHIC21_dataarray_data_V_writeaddr;
wire[20:0] VMPROJ_L3PHIC21_dataarray_data_V_din;
wire VMPROJ_L3PHIC21_nentries_0_V_we;
wire[7:0] VMPROJ_L3PHIC21_nentries_0_V_din;
wire VMPROJ_L3PHIC21_nentries_1_V_we;
wire[7:0] VMPROJ_L3PHIC21_nentries_1_V_din;
wire VMPROJ_L3PHIC21_dataarray_data_V_enb;
wire[7:0] VMPROJ_L3PHIC21_dataarray_data_V_readaddr;
wire[20:0] VMPROJ_L3PHIC21_dataarray_data_V_dout;
wire[7:0] VMPROJ_L3PHIC21_nentries_0_V_dout;
wire[7:0] VMPROJ_L3PHIC21_nentries_1_V_dout;

Memory #(
  .RAM_WIDTH(21),
  .RAM_DEPTH(256),
  .RAM_PERFORMANCE("HIGH_PERFORMANCE"),
  .HEX(0),
  .INIT_FILE("")
) VMPROJ_L3PHIC21 (
  .clka(clk),
  .clkb(clk),
//  .data_ena(VMPROJ_L3PHIC21_dataarray_data_V_ena),
  .data_wea(VMPROJ_L3PHIC21_dataarray_data_V_wea),
  .data_addra(VMPROJ_L3PHIC21_dataarray_data_V_writeaddr),
  .data_dina(VMPROJ_L3PHIC21_dataarray_data_V_din),
//  .nent_0_we(VMPROJ_L3PHIC21_nentries_0_V_we),
//  .nent_0_din(VMPROJ_L3PHIC21_nentries_0_V_din),
//  .nent_1_we(VMPROJ_L3PHIC21_nentries_1_V_we),
//  .nent_1_din(VMPROJ_L3PHIC21_nentries_1_V_din),
  .data_enb(VMPROJ_L3PHIC21_dataarray_data_V_enb),
  .data_addrb(VMPROJ_L3PHIC21_dataarray_data_V_readaddr),
  .data_doutb(VMPROJ_L3PHIC21_dataarray_data_V_dout),
//  .nent_0_dout(VMPROJ_L3PHIC21_nentries_0_V_dout),
//  .nent_1_dout(VMPROJ_L3PHIC21_nentries_1_V_dout),
  .regceb(1'b1)
);

wire ProjectionRouter_done;

SectorProcessor SectorProcessor_inst (
  .clk(clk),
  .reset(reset),
  .en_proc(en_proc),
  .bx_in_ProjectionRouter(bx_in_ProjectionRouter),
  .TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_enb(TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_enb),
  .TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_readaddr(TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_readaddr),
  .TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_dout(TPROJ_L1L2XXG_L3PHIC_dataarray_data_V_dout),
  .TPROJ_L1L2XXG_L3PHIC_nentries_0_V_dout(TPROJ_L1L2XXG_L3PHIC_nentries_0_V_dout),
  .TPROJ_L1L2XXG_L3PHIC_nentries_1_V_dout(TPROJ_L1L2XXG_L3PHIC_nentries_1_V_dout),
  .TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_enb(TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_enb),
  .TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_readaddr(TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_readaddr),
  .TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_dout(TPROJ_L1L2XXH_L3PHIC_dataarray_data_V_dout),
  .TPROJ_L1L2XXH_L3PHIC_nentries_0_V_dout(TPROJ_L1L2XXH_L3PHIC_nentries_0_V_dout),
  .TPROJ_L1L2XXH_L3PHIC_nentries_1_V_dout(TPROJ_L1L2XXH_L3PHIC_nentries_1_V_dout),
  .TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_enb(TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_enb),
  .TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_readaddr(TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_readaddr),
  .TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_dout(TPROJ_L5L6XXB_L3PHIC_dataarray_data_V_dout),
  .TPROJ_L5L6XXB_L3PHIC_nentries_0_V_dout(TPROJ_L5L6XXB_L3PHIC_nentries_0_V_dout),
  .TPROJ_L5L6XXB_L3PHIC_nentries_1_V_dout(TPROJ_L5L6XXB_L3PHIC_nentries_1_V_dout),
  .TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_enb(TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_enb),
  .TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_readaddr(TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_readaddr),
  .TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_dout(TPROJ_L5L6XXC_L3PHIC_dataarray_data_V_dout),
  .TPROJ_L5L6XXC_L3PHIC_nentries_0_V_dout(TPROJ_L5L6XXC_L3PHIC_nentries_0_V_dout),
  .TPROJ_L5L6XXC_L3PHIC_nentries_1_V_dout(TPROJ_L5L6XXC_L3PHIC_nentries_1_V_dout),
  .TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_enb(TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_enb),
  .TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_readaddr(TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_readaddr),
  .TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_dout(TPROJ_L5L6XXD_L3PHIC_dataarray_data_V_dout),
  .TPROJ_L5L6XXD_L3PHIC_nentries_0_V_dout(TPROJ_L5L6XXD_L3PHIC_nentries_0_V_dout),
  .TPROJ_L5L6XXD_L3PHIC_nentries_1_V_dout(TPROJ_L5L6XXD_L3PHIC_nentries_1_V_dout),
  .TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_enb(TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_enb),
  .TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_readaddr(TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_readaddr),
  .TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_dout(TPROJ_L1L2XXF_L3PHIC_dataarray_data_V_dout),
  .TPROJ_L1L2XXF_L3PHIC_nentries_0_V_dout(TPROJ_L1L2XXF_L3PHIC_nentries_0_V_dout),
  .TPROJ_L1L2XXF_L3PHIC_nentries_1_V_dout(TPROJ_L1L2XXF_L3PHIC_nentries_1_V_dout),
  .TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_enb(TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_enb),
  .TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_readaddr(TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_readaddr),
  .TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_dout(TPROJ_L1L2XXJ_L3PHIC_dataarray_data_V_dout),
  .TPROJ_L1L2XXJ_L3PHIC_nentries_0_V_dout(TPROJ_L1L2XXJ_L3PHIC_nentries_0_V_dout),
  .TPROJ_L1L2XXJ_L3PHIC_nentries_1_V_dout(TPROJ_L1L2XXJ_L3PHIC_nentries_1_V_dout),
  .TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_enb(TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_enb),
  .TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_readaddr(TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_readaddr),
  .TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_dout(TPROJ_L1L2XXI_L3PHIC_dataarray_data_V_dout),
  .TPROJ_L1L2XXI_L3PHIC_nentries_0_V_dout(TPROJ_L1L2XXI_L3PHIC_nentries_0_V_dout),
  .TPROJ_L1L2XXI_L3PHIC_nentries_1_V_dout(TPROJ_L1L2XXI_L3PHIC_nentries_1_V_dout),
  .bx_out_ProjectionRouter(bx_out_ProjectionRouter),
  .VMPROJ_L3PHIC20_dataarray_data_V_ena(VMPROJ_L3PHIC20_dataarray_data_V_ena),
  .VMPROJ_L3PHIC20_dataarray_data_V_wea(VMPROJ_L3PHIC20_dataarray_data_V_wea),
  .VMPROJ_L3PHIC20_dataarray_data_V_writeaddr(VMPROJ_L3PHIC20_dataarray_data_V_writeaddr),
  .VMPROJ_L3PHIC20_dataarray_data_V_din(VMPROJ_L3PHIC20_dataarray_data_V_din),
  .VMPROJ_L3PHIC20_nentries_0_V_we(VMPROJ_L3PHIC20_nentries_0_V_we),
  .VMPROJ_L3PHIC20_nentries_0_V_din(VMPROJ_L3PHIC20_nentries_0_V_din),
  .VMPROJ_L3PHIC20_nentries_1_V_we(VMPROJ_L3PHIC20_nentries_1_V_we),
  .VMPROJ_L3PHIC20_nentries_1_V_din(VMPROJ_L3PHIC20_nentries_1_V_din),
  .VMPROJ_L3PHIC17_dataarray_data_V_ena(VMPROJ_L3PHIC17_dataarray_data_V_ena),
  .VMPROJ_L3PHIC17_dataarray_data_V_wea(VMPROJ_L3PHIC17_dataarray_data_V_wea),
  .VMPROJ_L3PHIC17_dataarray_data_V_writeaddr(VMPROJ_L3PHIC17_dataarray_data_V_writeaddr),
  .VMPROJ_L3PHIC17_dataarray_data_V_din(VMPROJ_L3PHIC17_dataarray_data_V_din),
  .VMPROJ_L3PHIC17_nentries_0_V_we(VMPROJ_L3PHIC17_nentries_0_V_we),
  .VMPROJ_L3PHIC17_nentries_0_V_din(VMPROJ_L3PHIC17_nentries_0_V_din),
  .VMPROJ_L3PHIC17_nentries_1_V_we(VMPROJ_L3PHIC17_nentries_1_V_we),
  .VMPROJ_L3PHIC17_nentries_1_V_din(VMPROJ_L3PHIC17_nentries_1_V_din),
  .VMPROJ_L3PHIC22_dataarray_data_V_ena(VMPROJ_L3PHIC22_dataarray_data_V_ena),
  .VMPROJ_L3PHIC22_dataarray_data_V_wea(VMPROJ_L3PHIC22_dataarray_data_V_wea),
  .VMPROJ_L3PHIC22_dataarray_data_V_writeaddr(VMPROJ_L3PHIC22_dataarray_data_V_writeaddr),
  .VMPROJ_L3PHIC22_dataarray_data_V_din(VMPROJ_L3PHIC22_dataarray_data_V_din),
  .VMPROJ_L3PHIC22_nentries_0_V_we(VMPROJ_L3PHIC22_nentries_0_V_we),
  .VMPROJ_L3PHIC22_nentries_0_V_din(VMPROJ_L3PHIC22_nentries_0_V_din),
  .VMPROJ_L3PHIC22_nentries_1_V_we(VMPROJ_L3PHIC22_nentries_1_V_we),
  .VMPROJ_L3PHIC22_nentries_1_V_din(VMPROJ_L3PHIC22_nentries_1_V_din),
  .VMPROJ_L3PHIC19_dataarray_data_V_ena(VMPROJ_L3PHIC19_dataarray_data_V_ena),
  .VMPROJ_L3PHIC19_dataarray_data_V_wea(VMPROJ_L3PHIC19_dataarray_data_V_wea),
  .VMPROJ_L3PHIC19_dataarray_data_V_writeaddr(VMPROJ_L3PHIC19_dataarray_data_V_writeaddr),
  .VMPROJ_L3PHIC19_dataarray_data_V_din(VMPROJ_L3PHIC19_dataarray_data_V_din),
  .VMPROJ_L3PHIC19_nentries_0_V_we(VMPROJ_L3PHIC19_nentries_0_V_we),
  .VMPROJ_L3PHIC19_nentries_0_V_din(VMPROJ_L3PHIC19_nentries_0_V_din),
  .VMPROJ_L3PHIC19_nentries_1_V_we(VMPROJ_L3PHIC19_nentries_1_V_we),
  .VMPROJ_L3PHIC19_nentries_1_V_din(VMPROJ_L3PHIC19_nentries_1_V_din),
  .AP_L3PHIC_dataarray_data_V_ena(AP_L3PHIC_dataarray_data_V_ena),
  .AP_L3PHIC_dataarray_data_V_wea(AP_L3PHIC_dataarray_data_V_wea),
  .AP_L3PHIC_dataarray_data_V_writeaddr(AP_L3PHIC_dataarray_data_V_writeaddr),
  .AP_L3PHIC_dataarray_data_V_din(AP_L3PHIC_dataarray_data_V_din),
  .AP_L3PHIC_nentries_0_V_we(AP_L3PHIC_nentries_0_V_we),
  .AP_L3PHIC_nentries_0_V_din(AP_L3PHIC_nentries_0_V_din),
  .AP_L3PHIC_nentries_1_V_we(AP_L3PHIC_nentries_1_V_we),
  .AP_L3PHIC_nentries_1_V_din(AP_L3PHIC_nentries_1_V_din),
  .AP_L3PHIC_nentries_2_V_we(AP_L3PHIC_nentries_2_V_we),
  .AP_L3PHIC_nentries_2_V_din(AP_L3PHIC_nentries_2_V_din),
  .AP_L3PHIC_nentries_3_V_we(AP_L3PHIC_nentries_3_V_we),
  .AP_L3PHIC_nentries_3_V_din(AP_L3PHIC_nentries_3_V_din),
  .AP_L3PHIC_nentries_4_V_we(AP_L3PHIC_nentries_4_V_we),
  .AP_L3PHIC_nentries_4_V_din(AP_L3PHIC_nentries_4_V_din),
  .AP_L3PHIC_nentries_5_V_we(AP_L3PHIC_nentries_5_V_we),
  .AP_L3PHIC_nentries_5_V_din(AP_L3PHIC_nentries_5_V_din),
  .AP_L3PHIC_nentries_6_V_we(AP_L3PHIC_nentries_6_V_we),
  .AP_L3PHIC_nentries_6_V_din(AP_L3PHIC_nentries_6_V_din),
  .AP_L3PHIC_nentries_7_V_we(AP_L3PHIC_nentries_7_V_we),
  .AP_L3PHIC_nentries_7_V_din(AP_L3PHIC_nentries_7_V_din),
  .VMPROJ_L3PHIC24_dataarray_data_V_ena(VMPROJ_L3PHIC24_dataarray_data_V_ena),
  .VMPROJ_L3PHIC24_dataarray_data_V_wea(VMPROJ_L3PHIC24_dataarray_data_V_wea),
  .VMPROJ_L3PHIC24_dataarray_data_V_writeaddr(VMPROJ_L3PHIC24_dataarray_data_V_writeaddr),
  .VMPROJ_L3PHIC24_dataarray_data_V_din(VMPROJ_L3PHIC24_dataarray_data_V_din),
  .VMPROJ_L3PHIC24_nentries_0_V_we(VMPROJ_L3PHIC24_nentries_0_V_we),
  .VMPROJ_L3PHIC24_nentries_0_V_din(VMPROJ_L3PHIC24_nentries_0_V_din),
  .VMPROJ_L3PHIC24_nentries_1_V_we(VMPROJ_L3PHIC24_nentries_1_V_we),
  .VMPROJ_L3PHIC24_nentries_1_V_din(VMPROJ_L3PHIC24_nentries_1_V_din),
  .VMPROJ_L3PHIC23_dataarray_data_V_ena(VMPROJ_L3PHIC23_dataarray_data_V_ena),
  .VMPROJ_L3PHIC23_dataarray_data_V_wea(VMPROJ_L3PHIC23_dataarray_data_V_wea),
  .VMPROJ_L3PHIC23_dataarray_data_V_writeaddr(VMPROJ_L3PHIC23_dataarray_data_V_writeaddr),
  .VMPROJ_L3PHIC23_dataarray_data_V_din(VMPROJ_L3PHIC23_dataarray_data_V_din),
  .VMPROJ_L3PHIC23_nentries_0_V_we(VMPROJ_L3PHIC23_nentries_0_V_we),
  .VMPROJ_L3PHIC23_nentries_0_V_din(VMPROJ_L3PHIC23_nentries_0_V_din),
  .VMPROJ_L3PHIC23_nentries_1_V_we(VMPROJ_L3PHIC23_nentries_1_V_we),
  .VMPROJ_L3PHIC23_nentries_1_V_din(VMPROJ_L3PHIC23_nentries_1_V_din),
  .VMPROJ_L3PHIC18_dataarray_data_V_ena(VMPROJ_L3PHIC18_dataarray_data_V_ena),
  .VMPROJ_L3PHIC18_dataarray_data_V_wea(VMPROJ_L3PHIC18_dataarray_data_V_wea),
  .VMPROJ_L3PHIC18_dataarray_data_V_writeaddr(VMPROJ_L3PHIC18_dataarray_data_V_writeaddr),
  .VMPROJ_L3PHIC18_dataarray_data_V_din(VMPROJ_L3PHIC18_dataarray_data_V_din),
  .VMPROJ_L3PHIC18_nentries_0_V_we(VMPROJ_L3PHIC18_nentries_0_V_we),
  .VMPROJ_L3PHIC18_nentries_0_V_din(VMPROJ_L3PHIC18_nentries_0_V_din),
  .VMPROJ_L3PHIC18_nentries_1_V_we(VMPROJ_L3PHIC18_nentries_1_V_we),
  .VMPROJ_L3PHIC18_nentries_1_V_din(VMPROJ_L3PHIC18_nentries_1_V_din),
  .VMPROJ_L3PHIC21_dataarray_data_V_ena(VMPROJ_L3PHIC21_dataarray_data_V_ena),
  .VMPROJ_L3PHIC21_dataarray_data_V_wea(VMPROJ_L3PHIC21_dataarray_data_V_wea),
  .VMPROJ_L3PHIC21_dataarray_data_V_writeaddr(VMPROJ_L3PHIC21_dataarray_data_V_writeaddr),
  .VMPROJ_L3PHIC21_dataarray_data_V_din(VMPROJ_L3PHIC21_dataarray_data_V_din),
  .VMPROJ_L3PHIC21_nentries_0_V_we(VMPROJ_L3PHIC21_nentries_0_V_we),
  .VMPROJ_L3PHIC21_nentries_0_V_din(VMPROJ_L3PHIC21_nentries_0_V_din),
  .VMPROJ_L3PHIC21_nentries_1_V_we(VMPROJ_L3PHIC21_nentries_1_V_we),
  .VMPROJ_L3PHIC21_nentries_1_V_din(VMPROJ_L3PHIC21_nentries_1_V_din),
  .ProjectionRouter_done(ProjectionRouter_done)
);

endmodule
